basePath: /
definitions:
  echo.HTTPError:
    properties:
      message: {}
    type: object
  github_com_cutlery47_email-service_internal_models.ConfirmationData:
    properties:
      code:
        type: string
      mail:
        type: string
    type: object
  github_com_cutlery47_email-service_internal_models.UserData:
    properties:
      firstname:
        type: string
      mail:
        type: string
      nickname:
        type: string
      secondname:
        type: string
    type: object
info:
  contact:
    email: kitchen_cutlery@mail.ru
    name: Ivanchenko Arkhip
  description: This is an email authentication service
  title: Email Service
  version: 0.0.1
paths:
  /api/v1/confirm:
    post:
      parameters:
      - description: json
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/github_com_cutlery47_email-service_internal_models.ConfirmationData'
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Confirm Email
      tags:
      - Email
  /api/v1/register:
    post:
      parameters:
      - description: json
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/github_com_cutlery47_email-service_internal_models.UserData'
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Register User
      tags:
      - Email
swagger: "2.0"
