name: GitHub Actions Test

on:
    push:
        branches: ["master"]


jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Get sources
              uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v5

            - name: Build Go
              run: go build -v ./...

    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Run Tests
              run: go test ./internal/service


