name: GitHub Actions Test

on:
    push:
        branches: ["master"]


jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Get sources
              uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                go-version: '1.23.2'

            - name: Install Dependencies
              run: go mod download && go mod verify

            - name: Build Go
              run: go build -v ./...

    test:
        name: Test
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Debug dir
              run: ls 

            - name: Debug dir 2
              run: ls ${{ github.workspace }}

            - name: Run Tests
              run: go test -v ./...


